Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
    
]

pizzas/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza,name='pizza'),
    path('new_comment/<int:pizza_id>/',views.new_comment,name='new_comment'),
]

urlpatterns += staticfiles_urlpatterns()

pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)

    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return self.topping_name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    comment = models.TextField(max_length=300)

    def __str__(self):
        return self.comment

pizzas/forms.py
from django import forms

from .models import *

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        labels = {'comment':''}

        widgets = {'comment': forms. Textarea(attrs={'cols':80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
# Create your views here.

def index(request):
    """The home page for Pizzeria"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.all()

    context = {'pizzas':pizzas}
    # the key t is the variable that you are going to use on 
    # html page
    return render(request, 'pizzas/pizzas.html',context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = Topping.objects.filter(pizza=pizza)
    comments = Comment.objects.filter(pizza=pizza)
    context = {'pizza':pizza, 'toppings':toppings, 'comments':comments}

    return render(request, 'pizzas/pizza.html',context)


def new_comment(request, pizza_id):

    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        print(request.POST)
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            return redirect('pizzas:pizza',pizza_id=pizza_id)

    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizzas/new_comment.html',context)

pizzas/templates/pizzas/base.html
<title>Danny's Pizzeria</title>

<body style="background-color:rgb(238, 164, 103);">
<p>
<h1 style="font-family:serif;font-size:400%;text-align:center;">Danny's Pizzeria</h1>
<center><font size="+3"><a href="{% url 'pizzas:index' %}">Home</a>
<a href="{% url 'pizzas:pizzas' %}">Menu</a></font></center>
</p>

{% block content %}{% endblock content %}

</body>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}

{% load static %} 
<center><img src="{% static "pizzas/media/pizzalogo.jpg" %}" alt="Pizza Logo" width="650" height="500" /></center>
<p style="font-family:serif;font-size:200%;text-align:center;">Welcome to the Danny's Pizzeria Website</p>
<p style="font-family:serif;font-size:200%;text-align:center;">Where To Go For All The Knead-to-Know Information</p>


{% endblock content %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<p style="font-family:serif;font-size:200%;text-align:center;"><a href="{% url 'pizzas:pizza' pizza.id %}">{{pizza}}</a></p>

<p>Add a new comment:</p>

<form action="{% url 'pizzas:new_comment' pizza.id %}" method = "post">

    {% csrf_token %}

    {{ form.as_p }}

    <button name="Submit">Add Comment</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}
    {% load static %} 
    <p style="font-family:serif;font-size:200%;text-align:center;">Pizza: {{ pizza }}</p>

    {% if pizza.id == 1 %}
        <center><img src="{% static "pizzas/media/hawaiian.jpg" %}" alt="Pizza Logo" width="550" height="350" /></center>
    {% elif pizza.id == 2 %}
        <center><img src="{% static "pizzas/media/meatlovers.jpg" %}" alt="Pizza Logo" width="550" height="350" /></center>
    {% elif pizza.id == 4 %}
        <center><img src="{% static "pizzas/media/veggie.jpg" %}" alt="Pizza Logo" width="550" height="350" /></center>
    {% endif %}

    <p style="font-family:serif;font-size:150%;text-align:center;">Toppings</p>
    
    <html>
    <head>
    <style>
    div.container {
    text-align: center;
    }

    ul.myUL {
    display: inline-block;
    text-align: left;
    }
    </style>
    </head>
    <body>
    <div class="container">
        <ul class = "myUL">
            {% for t in toppings %}
            <li>
                <font size="+1">{{ t.topping_name }}</font>
            </li>
            {% empty %}
            <li> There are no toppings listed for this pizza yet. </li>
            {% endfor %}
        </ul>
    </div> 
    <p>
        Comments
    </p>
    <p>
        <a href="{% url 'pizzas:new_comment' pizza.id %}">Add a new comment</a>
    </p>
    <ul>
        {% for c in comments %}
        <li>
            <font size="+1">{{ c.comment }}</font>
        </li>
        {% empty %}
        <li> There are no comments for this pizza yet. </li>
        {% endfor %}

    </ul>
    
{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p style="font-family:serif;font-size:200%;text-align:center;">Pizzas</p>
    {% load static %} 
    <center><img src="{% static "pizzas/media/pizzahomepage.jpg" %}" alt="Pizza Homepage" width="550" height="350" /></center>

    <html>
    <head>
    <style>
    div.container {
    text-align: center;
    }

    ul.myUL {
    display: inline-block;
    text-align: left;
    }
    </style>
    </head>
    <body>
    <div class="container">
        <ul class="myUL">
            {% for pizza in pizzas %}
            <li>
                <font size="+2"><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></font>
            </li>
            {% empty %}
            <li>No pizzas have been added yet.</li>
            {% endfor %}
        </ul>
    </div>   
    
{% endblock content %}